# Generated by Django 5.2.1 on 2025-06-05 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PalabrasClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.CharField(max_length=1000)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('numero_paginas', models.IntegerField()),
                ('documento', models.FileField(upload_to='thesis/')),
                ('estado', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carreras')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodos')),
            ],
        ),
        migrations.CreateModel(
            name='TesisAutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autores')),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tesis')),
            ],
        ),
        migrations.CreateModel(
            name='TesisPalabrasClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabras_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.palabrasclave')),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tesis')),
            ],
        ),
    ]
